# Syntax-check Travis YAML .travis.yml files at http://lint.travis-ci.org
# Force Travis to rebuild by commiting an increment to this counter: 5

language: c

compiler:
  - gcc
  - clang
  - g++

before_install:
  - if [[ "${CC}" == "gcc" || "${CC}" == "g++" ]]; then export CXX=g++; fi
  - if [[ "${CC}" == "clang" || "${CC}" == "clang++" ]]; then export CXX=clang++; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq antlr libantlr-dev libnetcdf11 libnetcdf-dev netcdf-bin udunits-bin libudunits2-0 libudunits2-dev
  - ./configure
  - export DATA='/home/travis'

script:
  - make -j 4
  - make test
