c_compiler:
- vs2015
curl:
- '7.59'
cxx_compiler:
- vs2015
expat:
- '2.2'
gsl:
- '2.2'
hdf5:
- 1.10.2
libnetcdf:
- '4.6'
openblas:
- 0.2.20
pin_run_as_build:
  curl:
    max_pin: x
  expat:
    max_pin: x.x
  gsl:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  libnetcdf:
    max_pin: x.x
  openblas:
    max_pin: x.x.x
  vc:
    max_pin: x
  zlib:
    max_pin: x.x
vc:
- '14'
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
zlib:
- '1.2'
